### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by kgryte** [math-io/polynomial#1]
The current module name is `math-evalpoly`, but this is open for discussion.

**Comment by Planeshifter** [comment]
Looks all good to me, and personally I do prefer the coefficients to be supplied in **ascending** order. However, there is no agreement among different computing platforms: `numpy` and `Matlab` expect them in descending order, `Julia` and the `Boost C++` library in ascending order.

**Comment by kgryte** [comment]
@Planeshifter Ascending order it is. And the module name: `math-evalpoly`?

**Comment by Planeshifter** [comment]
No objections from me with regards to the name.

**Comment by kgryte** [comment]
Awesome. Thanks!
